"""Added phone number and OTP table

Revision ID: 169b27a682d2
Revises: c8cbb29513f2
Create Date: 2025-03-12 22:59:42.104464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '169b27a682d2'
down_revision: Union[str, None] = 'c8cbb29513f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
