"""Added new columns to tables

Revision ID: 21cd050d5ca9
Revises: 2aba97aa097f
Create Date: 2025-03-16 01:31:48.929550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21cd050d5ca9'
down_revision: Union[str, None] = '2aba97aa097f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broker_configs', sa.Column('clinet_id', sa.String(), nullable=True))
    op.add_column('broker_configs', sa.Column('access_token', sa.String(), nullable=True))
    op.add_column('broker_configs', sa.Column('refresh_token', sa.String(), nullable=True))
    op.alter_column('broker_configs', 'api_key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('broker_configs', 'api_secret',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('broker_configs', 'api_secret',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('broker_configs', 'api_key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('broker_configs', 'refresh_token')
    op.drop_column('broker_configs', 'access_token')
    op.drop_column('broker_configs', 'clinet_id')
    # ### end Alembic commands ###
