"""insert all stocks

Revision ID: 2a7973aa88bf
Revises: a9cb9fa798c8
Create Date: 2025-03-14 02:55:37.805005
"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from datetime import datetime

# revision identifiers, used by Alembic.
revision: str = '2a7973aa88bf'
down_revision: Union[str, None] = 'a9cb9fa798c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Table reference for the 'stocks' table
    stocks_table = sa.table(
        'stocks',
        sa.column('name', sa.String),
        sa.column('symbol', sa.String),
        sa.column('exchange', sa.String),
    )

    # Current timestamp for created_at and updated_at fields
    now = datetime.utcnow()

    # Prepare stock data for insertion with 'name' included
    stocks_data = [
        ('Indian Railway Finance Corporation', 'IRFC', 'NSE'),
        ('LT Finance', 'LTF', 'NSE'),
        ('CESC', 'CESC', 'NSE'),
        ('Bandhan Bank', 'BANDHANBNK', 'NSE'),
        ('GAIL India', 'GAIL', 'NSE'),
        ('Aditya Birla Capital', 'ABCAPITAL', 'NSE'),
        ('Federal Bank', 'FEDERALBNK', 'NSE'),
        ('Ashok Leyland', 'ASHOKLEY', 'NSE'),
        ('Zomato', 'ZOMATO', 'NSE'),
        ('Piramal Pharma', 'PPLPHARMA', 'NSE'),
        ('Manappuram Finance', 'MANAPPURAM', 'NSE'),
        ('Jio Financial Services', 'JIOFIN', 'NSE'),
        ('Oil and Natural Gas Corporation', 'ONGC', 'NSE'),
        ('Aditya Birla Fashion & Retail', 'ABFRL', 'NSE'),
        ('Delhivery', 'DELHIVERY', 'NSE'),
        ('Wipro', 'WIPRO', 'NSE'),
        ('Bharat Petroleum Corporation', 'BPCL', 'NSE'),
        ('Power Grid Corporation', 'POWERGRID', 'NSE'),
        ('Bharat Electronics', 'BEL', 'NSE'),
        ('Poonawalla Fincorp', 'POONAWALLA', 'NSE'),
        ('Biocon', 'BIOCON', 'NSE'),
        ('Hindustan Petroleum Corporation', 'HINDPETRO', 'NSE'),
        ('Indus Towers', 'INDUSTOWER', 'NSE'),
        ('NTPC', 'NTPC', 'NSE'),
        ('Tata Power', 'TATAPOWER', 'NSE'),
        ('Swiggy', 'SWIGGY', 'NSE'),
        ('Oil India', 'OIL', 'NSE'),
        ('Coal India', 'COALINDIA', 'NSE'),
        ('Aarti Industries', 'AARTIIND', 'NSE'),
        ('Birlasoft', 'BSOFT', 'NSE'),
        ('Power Finance Corporation', 'PFC', 'NSE'),
        ('REC Limited', 'RECLTD', 'NSE'),
        ('ITC', 'ITC', 'NSE'),
        ('Kalyan Jewellers', 'KALYANKJIL', 'NSE'),
        ('Vedanta', 'VEDL', 'NSE'),
        ('Granules India', 'GRANULES', 'NSE'),
        ('Balrampur Chini Mills', 'BALRAMCHIN', 'NSE'),
        ('Gujarat Narmada Valley Fertilizers', 'GNFC', 'NSE'),
        ('Sona BLW Precision Forgings', 'SONACOMS', 'NSE'),
        ('Ambuja Cements', 'AMBUJACEM', 'NSE'),
        ('Varun Beverages', 'VBL', 'NSE'),
        ('Berger Paints', 'BERGEPAINT', 'NSE'),
        ('Dabur India', 'DABUR', 'NSE'),
        ('AU Small Finance Bank', 'AUBANK', 'NSE'),
        ('Adani Power', 'ADANIPOWER', 'NSE'),
        ('JSW Energy', 'JSWENERGY', 'NSE'),
        ('ICICI Prudential Life Insurance', 'ICICIPRULI', 'NSE'),
        ('Sun TV Network', 'SUNTV', 'NSE'),
        ('Jubilant FoodWorks', 'JUBLFOOD', 'NSE'),
        ('CG Power and Industrial Solutions', 'CGPOWER', 'NSE'),
        ('UPL', 'UPL', 'NSE'),
        ('Can Fin Homes', 'CANFINHOME', 'NSE'),
        ('Adani Total Gas', 'ATGL', 'NSE'),
        ('Marico', 'MARICO', 'NSE'),
        ('Shriram Finance', 'SHRIRAMFIN', 'NSE'),
        ('HDFC Life Insurance', 'HDFCLIFE', 'NSE'),
        ('Container Corporation of India', 'CONCOR', 'NSE'),
        ('Tata Motors', 'TATAMOTORS', 'NSE'),
        ('DLF', 'DLF', 'NSE'),
        ('Syngene International', 'SYNGENE', 'NSE'),
        ('IndusInd Bank', 'INDUSINDBK', 'NSE'),
        ('Hindalco Industries', 'HINDALCO', 'NSE'),
        ('Paytm', 'PAYTM', 'NSE'),
        ('Titagarh Rail Systems', 'TITAGARH', 'NSE'),
        ('State Bank of India', 'SBIN', 'NSE'),
        ('Life Insurance Corporation of India', 'LICI', 'NSE'),
        ('Indian Hotels Company', 'INDHOTEL', 'NSE'),
        ('Adani Energy Solutions', 'ADANIENSOL', 'NSE'),
        ('Tata Chemicals', 'TATACHEM', 'NSE'),
        ('Ramco Cements', 'RAMCOCEM', 'NSE'),
        ('SBI Cards and Payment Services', 'SBICARD', 'NSE'),
        ('Adani Green Energy', 'ADANIGREEN', 'NSE'),
        ('Zydus Lifesciences', 'ZYDUSLIFE', 'NSE'),
        ('Piramal Enterprises', 'PEL', 'NSE'),
        ('Premier Energies', 'PREMIERENE', 'NSE'),
        ('Jindal Steel & Power', 'JINDALSTEL', 'NSE'),
        ('Tata Consumer Products', 'TATACONSUM', 'NSE'),
        ('Max Healthcare Institute', 'MAXHEALTH', 'NSE'),
        ('JSW Steel', 'JSWSTEEL', 'NSE'),
        ('Axis Bank', 'AXISBANK', 'NSE'),
        ('Godrej Consumer Products', 'GODREJCP', 'NSE'),
        ('Bharat Forge', 'BHARATFORG', 'NSE'),
        ('Max Financial Services', 'MFSL', 'NSE'),
        ('Macrotech Developers (Lodha)', 'LODHA', 'NSE'),
        ('Central Depository Services', 'CDSL', 'NSE'),
        ('Aurobindo Pharma', 'AUROPHARMA', 'NSE'),
        ('Dr. Reddy''s Laboratories', 'DRREDDY', 'NSE'),
        ('Adani Ports and Special Economic Zone', 'ADANIPORTS', 'NSE'),
        ('Prestige Estates Projects', 'PRESTIGE', 'NSE'),
        ('Godrej Industries', 'GODREJIND', 'NSE'),
        ('Cyient', 'CYIENT', 'NSE'),
        ('KPIT Technologies', 'KPITTECH', 'NSE'),
        ('Bata India', 'BATAINDIA', 'NSE'),
        ('Astral', 'ASTRAL', 'NSE'),
        ('Reliance Industries', 'RELIANCE', 'NSE'),
        ('ICICI Bank', 'ICICIBANK', 'NSE'),
        ('Mahanagar Gas', 'MGL', 'NSE'),
        ('Torrent Power', 'TORNTPOWER', 'NSE'),
        ('IPCA Laboratories', 'IPCALAB', 'NSE'),
        ('United Spirits', 'UNITDSPR', 'NSE'),
        ('APL Apollo Tubes', 'APLAPOLLO', 'NSE'),
        ('SBI Life Insurance', 'SBILIFE', 'NSE'),
        ('Voltas', 'VOLTAS', 'NSE'),
        ('Glenmark Pharmaceuticals', 'GLENMARK', 'NSE'),
        ('Tech Mahindra', 'TECHM', 'NSE'),
        ('Cholamandalam Investment and Finance', 'CHOLAFIN', 'NSE'),
        ('Havells India', 'HAVELLS', 'NSE'),
        ('Cipla', 'CIPLA', 'NSE'),
        ('Tata Communications', 'TATACOMM', 'NSE'),
        ('Oberoi Realty', 'OBEROIRLTY', 'NSE'),
        ('HCL Technologies', 'HCLTECH', 'NSE'),
        ('The Phoenix Mills', 'PHOENIXLTD', 'NSE'),
        ('Infosys', 'INFY', 'NSE'),
        ('Dalmia Bharat', 'DALBHARAT', 'NSE'),
        ('Metropolis Healthcare', 'METROPOLIS', 'NSE'),
        ('Bharti Airtel', 'BHARTIARTL', 'NSE'),
        ('ICICI Lombard General Insurance', 'ICICIGI', 'NSE'),
        ('Sun Pharmaceutical Industries', 'SUNPHARMA', 'NSE'),
        ('HDFC Bank', 'HDFCBANK', 'NSE'),
        ('Coromandel International', 'COROMANDEL', 'NSE'),
        ('Bajaj Finserv', 'BAJAJFINSV', 'NSE'),
        ('ACC', 'ACC', 'NSE'),
        ('United Breweries', 'UBL', 'NSE'),
        ('Deepak Nitrite', 'DEEPAKNTR', 'NSE'),
        ('Angel One', 'ANGELONE', 'NSE'),
        ('IndiaMART InterMESH', 'INDIAMART', 'NSE'),
        ('Lupin', 'LUPIN', 'NSE'),
        ('Godrej Properties', 'GODREJPROP', 'NSE'),
        ('Kotak Mahindra Bank', 'KOTAKBANK', 'NSE'),
        ('Hindustan Unilever', 'HINDUNILVR', 'NSE'),
        ('Nestle India', 'NESTLEIND', 'NSE'),
        ('Muthoot Finance', 'MUTHOOTFIN', 'NSE'),
        ('Mankind Pharma', 'MANKIND', 'NSE'),
        ('Mphasis', 'MPHASIS', 'NSE'),
        ('Adani Enterprises', 'ADANIENT', 'NSE'),
        ('Asian Paints', 'ASIANPAINT', 'NSE'),
        ('TVS Motor Company', 'TVSMOTOR', 'NSE'),
        ('Grasim Industries', 'GRASIM', 'NSE'),
        ('Colgate-Palmolive (India)', 'COLPAL', 'NSE'),
        ('Balkrishna Industries', 'BALKRISIND', 'NSE'),
        ('Dr. Lal PathLabs', 'LALPATHLAB', 'NSE'),
        ('Mahindra & Mahindra', 'M&M', 'NSE'),
        ('Pidilite Industries', 'PIDILITIND', 'NSE'),
        ('Cummins India', 'CUMMINSIND', 'NSE'),
        ('Escorts Kubota', 'ESCORTS', 'NSE'),
        ('Tube Investments of India', 'TIINDIA', 'NSE'),
        ('SRF', 'SRF', 'NSE'),
        ('Titan Company', 'TITAN', 'NSE'),
        ('KEI Industries', 'KEI', 'NSE'),
        ('Torrent Pharmaceuticals', 'TORNTPHARM', 'NSE'),
        ('Larsen & Toubro', 'LT', 'NSE'),
        ('PI Industries', 'PIIND', 'NSE'),
        ('Supreme Industries', 'SUPREMEIND', 'NSE'),
        ('Hindustan Aeronautics', 'HAL', 'NSE'),
        ('Tata Consultancy Services', 'TCS', 'NSE'),
        ('Hero MotoCorp', 'HEROMOTOCO', 'NSE'),
        ('HDFC Asset Management Company', 'HDFCAMC', 'NSE'),
        ('Avenue Supermarts (D-Mart)', 'DMART', 'NSE'),
        ('BSE', 'BSE', 'NSE'),
        ('Navin Fluorine International', 'NAVINFLUOR', 'NSE'),
        ('L&T Technology Services', 'LTTS', 'NSE'),
        ('LTIMindtree', 'LTIM', 'NSE'),
        ('InterGlobe Aviation (IndiGo)', 'INDIGO', 'NSE'),
        ('Alkem Laboratories', 'ALKEM', 'NSE'),
        ('Britannia Industries', 'BRITANNIA', 'NSE'),
        ('Multi Commodity Exchange of India', 'MCX', 'NSE'),
        ('Siemens', 'SIEMENS', 'NSE'),
        ('Polycab India', 'POLYCAB', 'NSE'),
        ('Eicher Motors', 'EICHERMOT', 'NSE'),
        ('Trent', 'TRENT', 'NSE'),
        ('ABB India', 'ABB', 'NSE'),
        ('Persistent Systems', 'PERSISTENT', 'NSE'),
        ('Tata Elxsi', 'TATAELXSI', 'NSE'),
        ('Atul', 'ATUL', 'NSE'),
        ('Divi''s Laboratories', 'DIVISLAB', 'NSE'),
        ('Crude Oil April 2025 Futures', 'CRUDEOIL25APRFUT', 'MCX'),
        ('Crude Oil March 2025 Futures', 'CRUDEOIL25MARFUT', 'MCX'),
        ('Apollo Hospitals Enterprise', 'APOLLOHOSP', 'NSE'),
        ('Info Edge (India) (Naukri)', 'NAUKRI', 'NSE'),
        ('Coforge', 'COFORGE', 'NSE'),
        ('Oracle Financial Services Software', 'OFSS', 'NSE'),
        ('Bajaj Auto', 'BAJAJ-AUTO', 'NSE'),
        ('Bajaj Finance', 'BAJFINANCE', 'NSE'),
        ('Solar Industries India', 'SOLARINDS', 'NSE'),
        ('UltraTech Cement', 'ULTRACEMCO', 'NSE'),
        ('Nifty Midcap 50 Index', 'MIDCPNIFTY-INDEX', 'NSE'),
        ('Maruti Suzuki India', 'MARUTI', 'NSE'),
        ('Dixon Technologies', 'DIXON', 'NSE'),
        ('Nifty 50 Index', 'NIFTY50-INDEX', 'NSE'),
        ('Nifty Financial Services Index', 'FINNIFTY-INDEX', 'NSE'),
        ('Bosch', 'BOSCHLTD', 'NSE'),
        ('Shree Cement', 'SHREECEM', 'NSE'),
        ('Abbott India', 'ABBOTINDIA', 'NSE'),
        ('Page Industries', 'PAGEIND', 'NSE'),
        ('Nifty Bank Index', 'NIFTYBANK-INDEX', 'NSE'),
        ('S&P BSE SENSEX', 'SENSEX-INDEX', 'BSE')
    ]
    
    # Bulk insert data into the stocks table
    op.bulk_insert(stocks_table, [
        {'name': stock[0], 'symbol': stock[1], 'exchange': stock[2]} 
        for stock in stocks_data
    ])


def downgrade():
    # Remove all the inserted stock records for NSE
    op.execute("DELETE FROM stocks WHERE exchange = 'NSE';")
