"""Updated broker config model

Revision ID: 2aba97aa097f
Revises: 2a7973aa88bf
Create Date: 2025-03-15 20:14:06.907061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aba97aa097f'
down_revision: Union[str, None] = '2a7973aa88bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broker_configs', sa.Column('access_token_expiry', sa.DateTime(), nullable=True))
    op.add_column('broker_configs', sa.Column('last_error_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broker_configs', 'last_error_message')
    op.drop_column('broker_configs', 'access_token_expiry')
    # ### end Alembic commands ###
