"""Added new columns correct name  to tables

Revision ID: 2c46fc4840e8
Revises: 21cd050d5ca9
Create Date: 2025-03-16 01:34:24.548821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c46fc4840e8'
down_revision: Union[str, None] = '21cd050d5ca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broker_configs', sa.Column('client_id', sa.String(), nullable=True))
    op.drop_column('broker_configs', 'clinet_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('broker_configs', sa.Column('clinet_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('broker_configs', 'client_id')
    # ### end Alembic commands ###
