"""Add strategy_id to trades

Revision ID: 67a4113d8625
Revises: 6119c367602f
Create Date: 2025-03-01 19:06:48.222827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = '67a4113d8625'
down_revision = '6119c367602f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trades', sa.Column('strategy_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trades', 'strategies', ['strategy_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trades', type_='foreignkey')
    op.drop_column('trades', 'strategy_id')
    # ### end Alembic commands ###