"""Fix foreign key user_id in Strategy

Revision ID: 70f2ab915938
Revises: 67a4113d8625
Create Date: 2025-03-01 19:09:21.575873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = '70f2ab915938'
down_revision = '67a4113d8625'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'strategies', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'strategies', type_='foreignkey')
    op.drop_column('strategies', 'user_id')
    # ### end Alembic commands ###