"""create broker_instruments table

Revision ID: faf3bb185f06
Revises: 9133ad8a8d45
Create Date: 2025-03-26 20:48:39.208238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'faf3bb185f06'
down_revision: Union[str, None] = '9133ad8a8d45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker_instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_name', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('segment', sa.String(), nullable=False),
    sa.Column('instrument_type', sa.String(), nullable=False),
    sa.Column('isin', sa.String(), nullable=True),
    sa.Column('lot_size', sa.Float(), nullable=True),
    sa.Column('tick_size', sa.Float(), nullable=True),
    sa.Column('instrument_key', sa.String(), nullable=False),
    sa.Column('security_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('broker_instruments')
    # ### end Alembic commands ###
