"""Add index to broker_instruments.symbol

Revision ID: fba3585819bc
Revises: faf3bb185f06
Create Date: 2025-03-27 00:30:48.982666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fba3585819bc'
down_revision: Union[str, None] = 'faf3bb185f06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_broker_instruments_exchange'), 'broker_instruments', ['exchange'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_broker_instruments_exchange'), table_name='broker_instruments')
    # ### end Alembic commands ###
