
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: market_data.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

# Manually adjusted stub since actual compiled content cannot be auto-generated here.
# This is just a placeholder to indicate a compiled proto file.

class LTPC(_message.Message):
    pass

class MarketLevel(_message.Message):
    pass

class MarketOHLC(_message.Message):
    pass

class Quote(_message.Message):
    pass

class OptionGreeks(_message.Message):
    pass

class OHLC(_message.Message):
    pass

class MarketFullFeed(_message.Message):
    pass

class IndexFullFeed(_message.Message):
    pass

class FullFeed(_message.Message):
    pass

class FirstLevelWithGreeks(_message.Message):
    pass

class Feed(_message.Message):
    pass

class MarketInfo(_message.Message):
    pass

class FeedResponse(_message.Message):
    pass

# Enum stubs
class Type:
    initial_feed = 0
    live_feed = 1
    market_info = 2

class RequestMode:
    ltpc = 0
    full_d5 = 1
    option_greeks = 2
    full_d30 = 3

class MarketStatus:
    PRE_OPEN_START = 0
    PRE_OPEN_END = 1
    NORMAL_OPEN = 2
    NORMAL_CLOSE = 3
    CLOSING_START = 4
    CLOSING_END = 5
